# Client-ID 获取文档https://developer.spotify.com/documentation/web-api/tutorials/client-credentials-flow
clientID: null

# Client-Secret 获取文档同上
clientSecret: null

# Access-Token 请求文档https://developer.spotify.com/documentation/web-api/tutorials/getting-started#request-an-access-token
accessToken: null